import localFont from "next/font/local";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import {AppProvider} from "../components/AppContext"
import { Toaster } from "react-hot-toast";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"], // Specify the subset
  weight: ["400", "500", "700"], // Include desired font weights
  variable: "--font-roboto", // Define a CSS variable for Roboto
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth" >
      <body className={`${roboto.variable} antialiased`}>
        <main className="max-w-4xl mx-auto  p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
              &copy; 2024 All rights reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
